services:
  mongo: 
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  app:
    build: ./app
    ports:
      - "5050:5000"
    env_file:
      - ./app/.env
    depends_on:
      - mongo

volumes:
  mongo_data: