name: resume-screener
region: sfo
features:
  - buildpack-stack=ubuntu-22

services:
  - name: gbs-4189-ml-client
    image:
      registry_type: DOCKER_HUB
      registry: gbs4189
      repository: ml-client
      tag: latest
    http_port: 5001
    internal_ports:
      - 5001
    run_command: python app.py
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    health_check:
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 5
      http_path: "/history"
      port: 5001

  - name: gbs-4189-web-app
    image:
      registry_type: DOCKER_HUB
      registry: gbs4189
      repository: web-app
      tag: latest
    http_port: 5000
    internal_ports:
      - 5000
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    health_check:
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 5
      http_path: "/"
      port: 5000

ingress:
  rules:
    - component:
        name: gbs-4189-web-app
      match:
        path:
          prefix: /

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
